name: 'Auto assign owner'
description: 'Automatically assigns owner on PR'
inputs:
  github-token:
    description: 'Github secret token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
