on: [pull_request]

jobs:
  example:
    runs-on: ubuntu-latest
    name: An example of auto-assign-author action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Auto assign author
        uses: ./ # Uses an action in the root directory
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
