on: [pull_request]

jobs:
  example:
    runs-on: ubuntu-latest
    name: An example of auto-assign-owner-action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Auto assign owner
        uses: danielswensson/auto-assign-owner-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
