on: [pull_request]

jobs:
  example:
    runs-on: ubuntu-latest
    name: An example of auto-assign-owner-action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Auto assign owner
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
